FROM ubuntu:22.04
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y vim git npm && \
    rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory '*'

RUN npm install -g conventional-changelog-cli@2.2.2

CMD ["conventional-changelog", "-p", "angular", "-i", "CHANGELOG.md", "-s"]
