FROM python:3.9 
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

WORKDIR /home

RUN pip install django

RUN django-admin startproject mysite

RUN sed -i "s/ALLOWED_HOSTS\ \=\ \[\]/ALLOWED_HOSTS\ =\ \[\'\*\'\]/" mysite/mysite/settings.py 

CMD ["python", "/home/mysite/manage.py", "runserver", "0.0.0.0:80"]

