FROM python:3.9 
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

ARG VERSION=latest
ARG DJANGO_VERSION=${VERSION}

WORKDIR /home

RUN if [ ${DJANGO_VERSION} = "latest" ] ; then pip install django ; else pip install django==${DJANGO_VERSION} ; fi

RUN django-admin startproject mysite

RUN sed -i "s/ALLOWED_HOSTS\ \=\ \[\]/ALLOWED_HOSTS\ =\ \[\'\*\'\]/" mysite/mysite/settings.py 

CMD ["python", "/home/mysite/manage.py", "runserver", "0.0.0.0:80"]

