FROM python:3.9
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

# Adapter
ARG VERSION=latest
ARG FLASK_VERSION=${VERSION}

WORKDIR /app

RUN if [ ${FLASK_VERSION} = "latest" ] ; then pip install flask gunicorn ; else pip install gunicorn flask==${FLASK_VERSION} ; fi

RUN mkdir /app/mysite

COPY mysite/ /app/mysite/

WORKDIR /app/mysite

CMD ["gunicorn", "-b :80", "wsgi:app"]
