name: Push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: asp.net
            version: latest
          - image: django
            version: "latest"
          - image: django
            version: "3"
          - image: django
            version: "2"
          - image: flask
            version: "latest"
          - image: flask
            version: "2"
          - image: flask
            version: "1"
          - image: conventional-changelog
            version: "latest"
          - image: rails
            version: "latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build \
            --no-cache \
            --rm \
            --file=${{ matrix.distribution.image }}/Dockerfile.${{ matrix.distribution.image }} \
            --tag=diodonfrost/hello-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} \
            --build-arg VERSION=${{ matrix.distribution.version }} \
            ${{ matrix.distribution.image }}

      - name: Push Docker image to Docker Hub
        run: |
          # Login on dockerhub.io before pushing
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pushing image to dockerhub
          docker push diodonfrost/hello-${{ matrix.distribution.image }}:${{ matrix.distribution.version }}

      - name: Push Docker image to Github Docker registry
        run: |
          # Login on Github Docker registry before pushing
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u diodonfrost --password-stdin

          # Pushing image to Github Docker registry
          docker tag diodonfrost/hello-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} docker.pkg.github.com/diodonfrost/hello-docker/hello-${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
          docker push docker.pkg.github.com/diodonfrost/hello-docker/hello-${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
